'use client'

import { useEffect, useState } from 'react'
import Image from 'next/image'
import Link from 'next/link'
import { useTheme } from 'next-themes'
import { motion } from 'framer-motion'
import { useForm } from 'react-hook-form'
import toast, { Toaster } from 'react-hot-toast'
import { ArrowRight, BarChart3, BookOpen, Briefcase, Building2, Github, Landmark, Linkedin, Mail, Menu, Moon, Sparkles, Sun, X } from 'lucide-react'
import { Button, Input, Textarea } from '@/components/ui'
import { articlesService, cvService, financeService, messagesService, metricsService, projectsService, researchService, settingsService, skillsService } from '@/lib/services'
import type { Article, CVFile, FinanceItem, Metric, Project, ResearchPublication, SiteSettings, Skill } from '@/types'

const fade = { initial: { opacity: 0, y: 18 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: '-80px' }, transition: { duration: .45 } }

function Header({ settings }: { settings: SiteSettings | null }) {
  const [open, setOpen] = useState(false)
  const [mounted, setMounted] = useState(false)
  const { theme, setTheme } = useTheme()
  useEffect(() => setMounted(true), [])
  const links = [['Home', '/#home'], ['About', '/#about'], ['Work', '/#work'], ['Finance & Strategy', '/finance'], ['Research', '/research'], ['Insights', '/insights'], ['Contact', '/#contact']]
  return <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#081018]/85 backdrop-blur-xl">
    <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-3 md:px-8">
      <Link href="/#home" className="flex min-h-11 items-center gap-3 rounded-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300">
        {settings?.profileImage && <span className="relative h-9 w-9 overflow-hidden rounded-full border border-white/15"><Image src={settings.profileImage} alt="" fill className="object-cover" /></span>}
        <span className="font-semibold tracking-tight text-white">Vishnuraj <span className="text-cyan-300">Vishwakarma</span></span>
      </Link>
      <nav aria-label="Primary navigation" className="hidden items-center gap-1 lg:flex">{links.map(([label, href]) => <Link key={label} href={href} className="rounded-lg px-3 py-3 text-sm text-slate-300 transition-colors hover:bg-white/5 hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300">{label}</Link>)}</nav>
      <div className="flex items-center gap-2">{mounted && <button aria-label="Toggle colour theme" onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')} className="flex h-11 w-11 items-center justify-center rounded-lg border border-white/10 text-slate-300 hover:bg-white/5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300">{theme === 'dark' ? <Sun size={18} /> : <Moon size={18} />}</button>}<button aria-label="Open navigation" aria-expanded={open} onClick={() => setOpen(!open)} className="flex h-11 w-11 items-center justify-center rounded-lg border border-white/10 text-white lg:hidden">{open ? <X size={20} /> : <Menu size={20} />}</button></div>
    </div>
    {open && <nav aria-label="Mobile navigation" className="border-t border-white/10 bg-[#081018] px-5 py-3 lg:hidden">{links.map(([label, href]) => <Link key={label} href={href} onClick={() => setOpen(false)} className="block min-h-11 rounded-lg px-3 py-3 text-sm text-slate-200 hover:bg-white/5">{label}</Link>)}</nav>}
  </header>
}

function SectionTitle({ eyebrow, title, copy }: { eyebrow: string, title: string, copy?: string }) {
  return <div className="mb-12 max-w-3xl"><p className="mb-4 text-xs font-semibold uppercase tracking-[.24em] text-cyan-300">{eyebrow}</p><h2 className="text-3xl font-semibold tracking-tight text-white sm:text-5xl">{title}</h2>{copy && <p className="mt-5 max-w-2xl text-base leading-7 text-slate-400 sm:text-lg">{copy}</p>}</div>
}

function Hero({ settings, metrics }: { settings: SiteSettings | null, metrics: Metric[] }) {
  const validMetrics = metrics.filter(metric => metric.visible !== false && metric.value?.trim() && !/^0(?:\.0+)?[+%]?$/.test(metric.value.trim()))
  return <section id="home" className="relative overflow-hidden border-b border-white/10 pt-28">
    <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_78%_18%,rgba(34,211,238,.12),transparent_28%),linear-gradient(rgba(255,255,255,.025)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.025)_1px,transparent_1px)] bg-[size:auto,48px_48px,48px_48px]" />
    <div className="relative mx-auto flex min-h-[70vh] max-w-7xl items-center px-5 py-16 md:px-8">
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .55 }}>
        <p className="mb-6 text-xs font-semibold uppercase tracking-[.28em] text-cyan-300">PGDM • Business • Technology</p>
        <h1 className="max-w-5xl text-5xl font-semibold leading-[1.02] tracking-[-.045em] text-white sm:text-7xl lg:text-[4.75rem]">Building Businesses with <span className="text-cyan-300">Data, Finance</span> & Technology.</h1>
        <p className="mt-7 max-w-3xl text-lg leading-8 text-slate-300">Founder & COO at Austrange Solutions. B.Sc IT graduate and PGDM candidate building AI-powered systems, analytics solutions, and business operations.</p>
        <div className="mt-9 flex flex-wrap gap-3"><Link href="/#work" className="inline-flex min-h-12 items-center gap-2 rounded-lg bg-cyan-300 px-6 py-3 text-sm font-semibold text-slate-950 hover:bg-cyan-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white">View My Work <ArrowRight size={17} /></Link><Link href="/#contact" className="inline-flex min-h-12 items-center rounded-lg border border-white/15 px-6 py-3 text-sm font-semibold text-white hover:bg-white/5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-300">Let&apos;s Connect</Link></div>
        <p className="mt-8 text-xs font-semibold uppercase tracking-[.22em] text-slate-400">Business Systems <span className="px-2 text-cyan-300">·</span> Analytics <span className="px-2 text-cyan-300">·</span> AI <span className="px-2 text-cyan-300">·</span> Operations</p>
      </motion.div>
    </div>
    {validMetrics.length > 0 && <div className="relative border-t border-white/10"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-px bg-white/10 md:grid-cols-4">{validMetrics.map(metric => <div key={metric.id} className="bg-[#081018] px-5 py-7 md:px-8"><p className="text-3xl font-semibold text-white">{metric.value}</p><p className="mt-1 text-xs uppercase tracking-wider text-slate-400">{metric.label}</p>{metric.description && <p className="mt-2 text-xs leading-5 text-slate-500">{metric.description}</p>}</div>)}</div></div>}
  </section>
}

function Positioning({ settings }: { settings: SiteSettings | null }) {
  return <section aria-label="Positioning" className="border-b border-white/10 bg-[#0a121b] px-5 md:px-8"><div className="mx-auto grid max-w-7xl gap-px bg-white/10 md:grid-cols-3">{['Business Builder.', 'Finance & Strategy Enthusiast.', 'Technology Entrepreneur.'].map((item, index) => <div key={item} className="bg-[#0a121b] px-5 py-7 md:px-8"><p className="text-xs uppercase tracking-[.2em] text-slate-500">0{index + 1}</p><p className="mt-3 text-lg font-medium text-white">{item}</p></div>)}</div>{(settings?.location || settings?.availability) && <p className="mx-auto max-w-7xl py-4 text-xs text-slate-500">{settings?.location}{settings?.availability ? ' · Open to opportunities' : ''}</p>}</section>
}

function About({ settings, skills }: { settings: SiteSettings | null, skills: Skill[] }) {
  const groups = ['Business', 'Analytics', 'Technology', 'Developing'].map(category => ({ category, items: skills.filter(skill => skill.category.toLowerCase() === category.toLowerCase()) }))
  const fallbacks: Record<string, string[]> = { Business: ['Operations', 'Strategy', 'Process Improvement', 'KPI Design'], Analytics: ['Excel', 'SQL', 'Power BI', 'Tableau', 'Python'], Technology: ['Next.js', 'TypeScript', 'Supabase', 'React', 'AI Systems'], Developing: ['Corporate Finance', 'Financial Modeling', 'Valuation', 'Investment Analysis'] }
  return <section id="about" className="border-b border-white/10 px-5 py-24 md:px-8"><div className="mx-auto max-w-7xl"><motion.div {...fade}><SectionTitle eyebrow="01 / About" title="I build systems that connect technology with business outcomes." copy="My work sits at the intersection of operations, analytics, AI-powered systems, technology, finance, and strategy. Technology is the means; clearer decisions and stronger businesses are the outcome." /></motion.div>{settings?.bio && <p className="mb-14 max-w-3xl whitespace-pre-line leading-8 text-slate-300">{settings.bio}</p>}<p className="mb-6 text-xs font-semibold uppercase tracking-[.22em] text-cyan-300">02 / Capabilities</p><div className="grid gap-px overflow-hidden rounded-xl border border-white/10 bg-white/10 md:grid-cols-2 lg:grid-cols-4">{groups.map(group => <div key={group.category} className="bg-[#0b141e] p-6"><h3 className="font-semibold text-white">{group.category}</h3><p className="mt-5 text-sm leading-7 text-slate-400">{(group.items.length ? group.items.map(skill => skill.name) : fallbacks[group.category]).join(' · ')}</p></div>)}</div></div></section>
}

function Work({ projects }: { projects: Project[] }) {
  const visible = projects.filter(project => project.visible !== false).sort((a, b) => Number(b.featured) - Number(a.featured)).slice(0, 6)
  if (!visible.length) return null
  return <section id="work" className="border-b border-white/10 bg-[#0a121b] px-5 py-24 md:px-8"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow="03 / Selected Work" title="Case studies, not a project gallery." copy="Problem → My Role → Solution → Technology → Business Impact → Evidence" /><div className="grid gap-5 lg:grid-cols-2">{visible.map((project, index) => <motion.article key={project.id} {...fade} className={`group overflow-hidden rounded-xl border border-white/10 bg-[#0d1722] ${index === 0 && project.featured ? 'lg:col-span-2' : ''}`}><div className="grid h-full md:grid-cols-[.8fr_1.2fr]">{project.imageUrl ? <div className="relative min-h-56 overflow-hidden"><Image src={project.imageUrl} alt={project.title} fill className="object-cover opacity-80 transition-transform duration-500 group-hover:scale-[1.03]" /></div> : <div className="flex min-h-48 items-center justify-center bg-white/[.025]"><BarChart3 className="text-cyan-300/50" size={46} /></div>}<div className="flex flex-col p-7"><p className="text-xs uppercase tracking-[.2em] text-cyan-300">{project.category || 'Technology'}</p><h3 className="mt-4 text-2xl font-semibold text-white">{project.title}</h3><p className="mt-4 flex-1 text-sm leading-7 text-slate-400">{project.summary || project.description}</p><div className="mt-6 flex flex-wrap gap-2">{project.stack.slice(0, 4).map(tool => <span key={tool} className="text-xs text-slate-500">{tool}</span>)}</div><Link href={`/case-studies/${project.slug || project.id}`} className="mt-7 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-white hover:text-cyan-300">Read case study <ArrowRight size={16} /></Link></div></div></motion.article>)}</div></div></section>
}

function Proof({ settings, projects, finance, research }: { settings: SiteSettings | null, projects: Project[], finance: FinanceItem[], research: ResearchPublication[] }) {
  const items = [
    settings?.academicProofUrl ? { label: 'Academic record', title: 'B.Sc IT — SGPA 9.4', href: settings.academicProofUrl } : null,
    settings?.companyUrl ? { label: 'Company / product', title: 'Austrange Solutions', href: settings.companyUrl } : null,
    ...projects.filter(item => item.visible !== false && (item.proofUrl || item.liveUrl || item.githubUrl)).map(item => ({ label: 'Case study evidence', title: item.title, href: item.proofUrl || item.liveUrl || item.githubUrl || '' })),
    ...research.filter(item => item.visible !== false && (item.publicationUrl || item.documentUrl)).map(item => ({ label: 'Publication', title: item.title, href: item.publicationUrl || item.documentUrl || '' })),
    ...finance.filter(item => item.visible !== false && (item.documentUrl || item.externalUrl)).map(item => ({ label: 'Finance analysis', title: item.title, href: item.documentUrl || item.externalUrl || '' }))
  ].filter((item): item is { label: string, title: string, href: string } => Boolean(item?.href))
  if (!items.length) return null
  return <section id="proof" className="border-b border-white/10 px-5 py-20 md:px-8"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow="Proof" title="Claims connected to evidence." copy="Credentials, publications, products, source code, and analysis—linked where they can be verified." /><div className="divide-y divide-white/10 border-y border-white/10">{items.slice(0, 8).map(item => <a key={`${item.label}-${item.title}`} href={item.href} target="_blank" rel="noreferrer" className="group flex min-h-20 items-center justify-between gap-5 py-5"><span><span className="text-xs uppercase tracking-[.18em] text-slate-500">{item.label}</span><span className="mt-1 block font-medium text-white">{item.title}</span></span><ArrowRight className="shrink-0 text-slate-600 group-hover:text-cyan-300" size={18} /></a>)}</div></div></section>
}

function FocusSections({ finance, research, articles, nowText }: { finance: FinanceItem[], research: ResearchPublication[], articles: Article[], nowText?: string }) {
  const capabilities = ['Corporate Finance', 'Financial Analysis', 'Valuation', 'Business Strategy', 'Market Analysis', 'Negotiation']
  const visibleFinance = finance.filter(i => i.visible !== false), visibleResearch = research.filter(i => i.visible !== false), visibleArticles = articles.filter(i => i.visible !== false)
  return <><section id="finance" className="border-b border-white/10 px-5 py-24 md:px-8"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow="04 / Developing Expertise" title="Finance & Strategy" copy="Building expertise in finance and strategy through PGDM coursework, company analysis, research, financial modeling, and practical projects." /><div className="mb-10 flex flex-wrap gap-2">{capabilities.map(item => <span key={item} className="rounded-full border border-white/10 px-4 py-2 text-sm text-slate-300">{item}</span>)}</div>{visibleFinance.slice(0, 3).map(item => <Link key={item.id} href="/finance" className="group flex min-h-20 items-center justify-between border-t border-white/10 py-5"><span><span className="text-xs uppercase tracking-wider text-cyan-300">{item.category}</span><span className="mt-1 block text-lg font-medium text-white">{item.title}</span></span><ArrowRight className="text-slate-600 group-hover:text-cyan-300" /></Link>)}<Link href="/finance" className="mt-8 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-white hover:text-cyan-300">Explore finance & strategy <ArrowRight size={16} /></Link></div></section>
    {visibleResearch.length > 0 && <section id="research" className="border-b border-white/10 bg-[#0a121b] px-5 py-24 md:px-8"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow="06 / Research" title="Research & Publications" copy="Research is presented with its authorship, venue, abstract, and source links—so credibility stays attached to evidence." /><div className="grid gap-5 md:grid-cols-2">{visibleResearch.slice(0, 4).map(item => <article key={item.id} className="rounded-xl border border-white/10 bg-[#0d1722] p-7"><BookOpen className="text-cyan-300" size={22} /><p className="mt-6 text-xs uppercase tracking-wider text-slate-500">{item.researchArea || 'Research'} {item.year ? `· ${item.year}` : ''}</p><h3 className="mt-2 text-xl font-semibold text-white">{item.title}</h3><p className="mt-4 text-sm leading-7 text-slate-400">{item.summary}</p></article>)}</div><Link href="/research" className="mt-8 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-white hover:text-cyan-300">View research <ArrowRight size={16} /></Link></div></section>}
    {visibleArticles.length > 0 && <section id="insights" className="border-b border-white/10 px-5 py-24 md:px-8"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow="07 / Insights" title="What I&apos;m Learning & Building" copy="Notes and essays on business, finance, technology, AI, strategy, and analytics." /><div className="grid gap-5 md:grid-cols-3">{visibleArticles.slice(0, 3).map(item => <Link key={item.id} href={`/insights/${item.slug}`} className="rounded-xl border border-white/10 p-6 hover:bg-white/[.03]"><p className="text-xs uppercase tracking-wider text-cyan-300">{item.category}</p><h3 className="mt-4 text-xl font-semibold text-white">{item.title}</h3><p className="mt-4 text-sm leading-7 text-slate-400">{item.excerpt}</p></Link>)}</div><Link href="/insights" className="mt-8 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-white hover:text-cyan-300">Browse all insights <ArrowRight size={16} /></Link></div></section>}
    <section id="now" className="border-b border-white/10 bg-cyan-300 px-5 py-14 text-slate-950 md:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-5 md:flex-row md:items-start"><Sparkles className="mt-1 shrink-0" /><div><p className="text-xs font-semibold uppercase tracking-[.24em]">Now</p><p className="mt-3 max-w-4xl text-xl font-medium leading-8">{nowText || 'Currently pursuing PGDM while building AI-powered business systems and developing deeper expertise in finance, strategy, analytics, and operations.'}</p></div></div></section></>
}

function Experience() {
  const items = [{ organization: 'Austrange Solutions Pvt Ltd', role: 'Founder & COO', date: 'Dec 2025 — Present', responsibilities: 'Business operations, product development, team coordination, SOPs, budgeting, and go-to-market planning.', functions: 'Operations · Analytics · Technology' }, { organization: 'Vishnushakti Foundation', role: 'Web Developer / Analyst', date: 'Jan 2024 — Jan 2025', responsibilities: 'Improved responsive web portals and automated administrative workflows with Google Apps Script and structured datasets.', functions: 'Web · Automation · Data' }, { organization: 'Dr. Shuhila Gandhi Skill Center · UAV Pharmaceuticals', role: 'Business Analytics Program', date: '2024', responsibilities: 'Training in business analytics, KPI frameworks, and Power BI dashboarding.', functions: 'Analytics · KPI Design' }]
  return <section className="border-b border-white/10 bg-[#0a121b] px-5 py-24 md:px-8"><div className="mx-auto max-w-5xl"><SectionTitle eyebrow="08 / Leadership Journey" title="Experience shaped by ownership." /><div>{items.map(item => <article key={item.organization} className="grid gap-3 border-t border-white/10 py-8 md:grid-cols-[180px_1fr]"><p className="text-sm text-slate-500">{item.date}</p><div><h3 className="text-xl font-semibold text-white">{item.role}</h3><p className="mt-1 text-cyan-300">{item.organization}</p><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-400">{item.responsibilities}</p><p className="mt-4 text-xs uppercase tracking-wider text-slate-500">{item.functions}</p></div></article>)}</div></div></section>
}

function Contact({ settings, cv }: { settings: SiteSettings | null, cv: CVFile | null }) {
  const { register, handleSubmit, reset, formState: { isSubmitting } } = useForm()
  const submit = async (data: any) => { try { await messagesService.create(data); toast.success('Message received.'); reset() } catch { toast.error('Could not send your message. Please try again.') } }
  const paths = [{ icon: Briefcase, title: 'Recruiters', copy: 'Internships, business analytics, strategy, finance, and technology opportunities.' }, { icon: Building2, title: 'Businesses', copy: 'AI automation, analytics, operational systems, and digital transformation.' }, { icon: Landmark, title: 'Collaborations', copy: 'Research, startups, finance, strategy, and technology collaborations.' }]
  return <section id="contact" className="px-5 py-24 md:px-8"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow="09 / Contact" title="Choose the right conversation." /><div className="mb-12 grid gap-4 md:grid-cols-3">{paths.map(path => <div key={path.title} className="rounded-xl border border-white/10 p-6"><path.icon className="text-cyan-300" size={22} /><h3 className="mt-5 font-semibold text-white">{path.title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{path.copy}</p></div>)}</div><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-sm leading-7 text-slate-400">Have a relevant opportunity, business problem, or research idea? Send a concise note and it will arrive in the existing Admin Inbox.</p><div className="mt-7 flex flex-col gap-2">{settings?.email && <a className="inline-flex min-h-11 items-center gap-3 text-sm text-white hover:text-cyan-300" href={`mailto:${settings.email}`}><Mail size={17} />{settings.email}</a>}{settings?.linkedinUrl && <a className="inline-flex min-h-11 items-center gap-3 text-sm text-white hover:text-cyan-300" href={settings.linkedinUrl} target="_blank" rel="noreferrer"><Linkedin size={17} />LinkedIn</a>}{settings?.githubUrl && <a className="inline-flex min-h-11 items-center gap-3 text-sm text-white hover:text-cyan-300" href={settings.githubUrl} target="_blank" rel="noreferrer"><Github size={17} />GitHub</a>}{cv?.url && <a className="mt-3 inline-flex min-h-11 items-center text-sm font-semibold text-cyan-300" href={cv.url} target="_blank" rel="noreferrer">View résumé <ArrowRight className="ml-2" size={16} /></a>}</div></div><form onSubmit={handleSubmit(submit)} className="grid gap-5 rounded-xl border border-white/10 bg-[#0d1722] p-6 sm:grid-cols-2"><Input label="Name / Organization" autoComplete="name" {...register('name', { required: true })} /><Input label="Email" type="email" autoComplete="email" {...register('email', { required: true })} /><div className="sm:col-span-2"><Input label="Subject" {...register('subject')} /></div><div className="sm:col-span-2"><Textarea label="Message" {...register('message', { required: true })} /></div><Button type="submit" loading={isSubmitting} className="sm:col-span-2 bg-cyan-300 text-slate-950 hover:bg-cyan-200">Send message</Button></form></div></div></section>
}

export default function PortfolioPage() {
  const [settings, setSettings] = useState<SiteSettings | null>(null)
  const [metrics, setMetrics] = useState<Metric[]>([]), [projects, setProjects] = useState<Project[]>([]), [skills, setSkills] = useState<Skill[]>([])
  const [finance, setFinance] = useState<FinanceItem[]>([]), [research, setResearch] = useState<ResearchPublication[]>([]), [articles, setArticles] = useState<Article[]>([]), [cv, setCV] = useState<CVFile | null>(null)
  useEffect(() => { const unsubs = [settingsService.subscribe(setSettings), metricsService.subscribe(setMetrics), projectsService.subscribe(setProjects, true), skillsService.subscribe(setSkills), financeService.subscribe(setFinance), researchService.subscribe(setResearch), articlesService.subscribe(setArticles)]; cvService.getActive().then(setCV); return () => unsubs.forEach(unsub => unsub()) }, [])
  return <main className="min-h-screen overflow-x-hidden bg-[#081018] text-white"><Toaster position="bottom-right" /><Header settings={settings} /><Hero settings={settings} metrics={metrics} /><Positioning settings={settings} /><About settings={settings} skills={skills} /><Work projects={projects} /><Proof settings={settings} projects={projects} finance={finance} research={research} /><FocusSections finance={finance} research={research} articles={articles} nowText={settings?.nowText} /><Experience /><Contact settings={settings} cv={cv} /><footer className="border-t border-white/10 px-5 py-8 text-center text-sm text-slate-500 md:px-8">© {new Date().getFullYear()} Vishnuraj Vishwakarma · Business Builder · Finance & Strategy · Technology Entrepreneur</footer></main>
}
