import type { Metadata } from 'next'
import Image from 'next/image'
import { notFound } from 'next/navigation'
import { EditorialPage } from '@/components/public/EditorialPage'
import { supabase } from '@/lib/supabase'
export const dynamic = 'force-dynamic'
async function getCaseStudy(slug: string) { let query = supabase.from('projects').select('*'); const byId = /^[0-9a-f-]{30,}$/i.test(slug); query = byId ? query.eq('id', slug) : query.eq('slug', slug); const { data } = await query.single(); return data }
export async function generateMetadata({ params }: { params: { slug: string } }): Promise<Metadata> { const item = await getCaseStudy(params.slug); if (!item) return {}; return { title: `${item.title} | Case Study`, description: item.summary || item.description, alternates: { canonical: `/case-studies/${item.slug || item.id}` }, openGraph: { title: item.title, description: item.summary || item.description, images: item.imageUrl ? [item.imageUrl] : undefined } } }
export default async function CaseStudyPage({ params }: { params: { slug: string } }) { const item = await getCaseStudy(params.slug); if (!item || item.visible === false) notFound(); const blocks = [['Problem', item.problem], ['My Role', item.role], ['Solution', item.approach], ['Business Impact', item.businessImpact], ['Evidence', item.results]].filter(([, value]) => value); return <EditorialPage eyebrow={item.category || 'Case Study'} title={item.title} intro={item.summary || item.description}>{item.imageUrl && <div className="relative mb-14 aspect-[16/8] overflow-hidden rounded-xl border border-white/10"><Image src={item.imageUrl} alt={item.title} fill className="object-cover" priority /></div>}<div className="grid gap-8 md:grid-cols-2">{blocks.map(([label, value]) => <section key={label} className="border-t border-white/10 pt-6"><h2 className="text-xs font-semibold uppercase tracking-[.2em] text-cyan-300">{label}</h2><p className="mt-4 whitespace-pre-wrap text-base leading-8 text-slate-300">{value}</p></section>)}</div>{item.stack?.length > 0 && <section className="mt-12 border-t border-white/10 pt-6"><h2 className="mb-4 text-xs font-semibold uppercase tracking-[.2em] text-cyan-300">Technology</h2><div className="flex flex-wrap gap-2">{item.stack.map((tool: string) => <span key={tool} className="rounded-full border border-white/10 px-4 py-2 text-sm text-slate-300">{tool}</span>)}</div></section>}</EditorialPage> }
